# Site settings
title: Horus, IOT without infrastructure change
tag_text: Horus
description: Horus is a Senior Design Project(CS 491) which aims to be an interim technology connecting current sensor tracking infrastrucre to the cloud. 

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
